### PR TITLE
Prevent React setState on unmounted Component

### PR DESCRIPTION
**Pull request by milanito**
# Description

Hello @timhagn 

I have came across the `Can't perform a React state update on an unmounted component.` error when using this module when using it with conditional components.

In order to prevent it, I added an `_isMounted` field in the `BackgroundImage` class to check if the component is mounted or not

Cheers !

### CODE REVIEW

**Comment by timhagn** [comment]
Thanks a lot, that slipped my attention oO! Merged instantly : ).

**Comment by timhagn** [comment]
@milanito You might have solve issue #16 in the process, or can you replicate it anymore at your place?

**Comment by milanito** [comment]
@timhagn I’ll check that when I get back home

**Comment by timhagn** [comment]
@milanito Sadly, you won't have to. As @petrpacas already commented in #16, the issue persists : /.

**Comment by timhagn** [comment]
Hi @milanito,
I just published `v0.5.0` with many fixes, refactoring and code coverage (now at 100% : ).
In the process I removed the "anti-pattern" of `_isMounted | isMounted` in favor for setting `imageRef.onload` to `null` on component unmount.
Would you mind checking it with your use case, that would be great : )!
Thanks in advance,
Tim.

**Pull request merged**
