### PR TITLE
Per fix for IntersectionObserver detection

### PR DESCRIPTION
**Pull request by bre7**
## Description

Minor perf fix for IntersectionObserver detection

### CODE REVIEW

**Comment by bre7** [comment]
👍

**Comment by timhagn** [comment]
Hi @bre7 / Nathan!

Thanks a lot for spotting this, creating a PR and reacting damn fast : )!
Merged and integrated in the just published `v0.9.9`!

Thanks again,

best,

Tim.

**Comment by bre7** [comment]
No worries ;) Thanks for the lib

**Comment by bre7** [comment]
Update: https://eslint.org/docs/rules/no-negated-in-lhs

It still works but it'd probably be better to use `(!(`IntersectionObserver` in window))` to avoid the ESLint warning

**Comment by timhagn** [comment]
Thanks a lot for noticing, changed it (next to some other tweaks) and just published it as `v0.9.11` : ).

**Pull request merged**
