### PR TITLE
Bump react version to allow 18

### LINKED ISSUE #176: Upgrade gbimage-bridge to React 18
## Summary

I would very much appreciate a bump of gbimage-bridge to React 18 as staying up to date is necessary to provide a usable plugin.

### Motivation

Why should this be supported?  Because it makes life much easier when having a lot of plugins installed to stay up to date with all dependencies.

### PR DESCRIPTION
**Pull request by devzeebo**
## Description

Bump the React and React DOM peer dependencies to allow React 18

## Related Issues

Fixes #176

### CODE REVIEW

**Comment by pkuczynski** [comment]
@timhagn any chance to get this merged and released? Otherwise, npm complains during install of newer version of gatsby.

**Review by timhagn — APPROVED** [review]
Sry for taking so long, am more than fully booked since some time.
LGTM!

**Comment by timhagn** [comment]
Just published `gbimage-bridge@v0.2.2`.

**Comment by pkuczynski** [comment]
Works, thanks! :)

**Pull request merged**
