### PR TITLE
Replaced the use of StaticQuery in demo with static query hook

### PR DESCRIPTION
**Pull request by nina-py**
## Description

The first demo of the plugin in the README file uses the old StaticQuery component instead of a hook. I propose changing this demo to use the static query hook as well as it improves code readability.

### CODE REVIEW

**Review by timhagn — CHANGES_REQUESTED** [review]
Hi Nina,
thanks for this one - though I would have at least one usage with `StaticQuery` still in the README, as `gatsby` still only has a peer dependency of:

```json
  "peerDependencies": {
    "react": "^16.4.2",
    "react-dom": "^16.4.2"
  },
```

What do you think? Just duplicating the fragment with a text like "or you may do it the old way like..."?
Either way, the README of `gbi` without `-es5` would have to be updated as well ; ).

Thanks again for your contribution : )!

Best,

Tim.

**Comment by nina-py** [comment]
Hi Tim, good point - my main motivation to change this example to the useStaticQuery hook was that it was the very first example in the plugin documentation and I thought it would be much easier to understand this way. I have reinstated the StaticQuery examples, placing them after the hook ones.

> Either way, the README of gbi without -es5 would have to be updated as well ; ).

You might have to handhold me through this as I didn't find anything else related to this pull request that I could update. Although while looking, I picked up a few typos in the text and fixed them as well.

**Review by timhagn — APPROVED** [review]
Hi Nina,

wowzers, that's great, thanks a lot : )! I'm a little ashamed about all the `it's` vs `its` typos I made. Though not my first language, I shouldn't make these in English that often % ).

LGTM! Thanks again (and where now should I've had to hold your hand? You exceeded my change request by far ; )!

Best,

Tim.

**Comment by timhagn** [comment]
Oh, and sorry, my bad - completely overlooked that you already had changed both README's ^^.

Thanks again!

**Comment by nina-py** [comment]
Hi Tim,

Ah I see - yes, I did go for both the READMEs in the initial commit, and thought I might have missed some in the test suite or elsewhere based on your follow-up comments. Glad to be of service! :)

Nina

**Pull request merged**
