### PR TITLE
fix: collision classname.

### LINKED ISSUE #55: Consecutive images with the same source cause the first one to not load until user scrolls
## Description

When I place two `BackgroundImage`s consecutively, the first one will only load once the second one has been scrolled to in a **production build**.

### Steps to reproduce

Place two images a fair distance apart consecutively on a page with the same fluid source like so:
```jsx
<BackgroundImage
  style={{width: '100%', height: '100vh'}}
  fluid={backgroundFile.childImageSharp.fluid}
/>

<div
  style={{width: '100%', height: '100vh'}}
/>

<BackgroundImage
  style={{width: '100%', height: '100vh'}}
  fluid={backgroundFile.childImageSharp.fluid}
/>
```
...assuming `backgroundFile` is populated by a GraphQL query with the Sharp image.
Then run `npm run build` and `npm run serve`.

### Expected result

At least the top image should load when in the viewport.

### Actual result

The top image only loaded once the bottom image was in the viewport

### Environment
```
  System:
    OS: Linux [redacted other info]
  Binaries:
    Node: 10.11.0 - /usr/local/bin/node
    npm: 6.4.1 - /usr/local/bin/npm
  Languages:
    Python: 2.7.12 - /usr/bin/python
  Browsers:
    [redacted]
  npmPackages:
    gatsby: 2.13.41 => 2.13.41
    gatsby-background-image-es5: ^0.8.0 => 0.8.0
    gatsby-image: ^2.2.7 => 2.2.7
    gatsby-plugin-manifest: 2.2.4 => 2.2.4
    gatsby-plugin-postcss: 2.1.2 => 2.1.2
    gatsby-plugin-purgecss: 4.0.0 => 4.0.0
    gatsby-plugin-react-helmet: 3.1.2 => 3.1.2
    gatsby-plugin-sharp: ^2.2.9 => 2.2.9
    gatsby-source-directus7: ^0.8.1 => 0.8.1
    gatsby-source-filesystem: ^2.1.6 => 2.1.6
    gatsby-transformer-sharp: ^2.2.4 => 2.2.4
  npmGlobalPackages:
    gatsby-cli: 2.7.0
```

### PR DESCRIPTION
**Pull request by hikouki**
## Description

I was collided classname.

`Math.random() * 42` is collision with high probability.

Alternative: uuid v4.

Please merge If you like ✈️ 

**Like this.**

スクリーンショット 2019-09-20 0 45 47

## Related Issues

Fixes #55

### CODE REVIEW

**Comment by timhagn** [comment]
Hi @kikouki,

thanks a friggin lot : )! You're the first to write tests in a PR to this (meanwhile growing ; ) "nifty little package"!
Can't review it right now, am on mobile, but gonna try checking it out tomorrow.
The only thing that'd be good to know, has `uuid` a "short-mode"? Have only worked with it in DB / JSON contexts. I just don't want to explode users HTML Download-Size more than `gbi` already does now ; ).

And though your PR would be ruining the `Hitchhiker's guide to the Galaxy` pun, I'd be more than happy to merge it ^^!

Thanks again,

Tim.

**Comment by hikouki** [comment]
Thank you for reply :)

Sorry, I don't know `Hitchhiker's guide to the Galaxy` pun inside out...

> Have only worked with it in DB / JSON contexts. I just don't want to explode users HTML Download-Size more than gbi already does now ; ).

I see. I think so too.
Let me think about it.

> EDIT2: Why the push --force commits oO?

Bundle A and make the review easier.

**Comment by timhagn** [comment]
Hi @hikouki!

Just searched a little and it seems to me that [short-uuid](https://www.npmjs.com/package/short-uuid) would be a great solution, what do you think?

And about the "pun" on 42 just have a look at [Wikipedia's 42 article](https://en.wikipedia.org/wiki/42_(number)#The_Hitchhiker's_Guide_to_the_Galaxy) or the direct link to a Japanese (did I guess your language correctly? % ) version of it's [Hitchhiker's Guide page](https://ja.wikipedia.org/wiki/%E9%8A%80%E6%B2%B3%E3%83%92%E3%83%83%E3%83%81%E3%83%8F%E3%82%A4%E3%82%AF%E3%83%BB%E3%82%AC%E3%82%A4%E3%83%89) : ).

Thanks again for your contribution!

Best,

Tim.

**Comment by hikouki** [comment]
Good idea 👍 

I will use `short-uuid`.

Thank you for telling me about 42!
I understand it :)

**Comment by timhagn** [comment]
Hi @hikouki,

looks awesome, thanks a lot again, gonna merge it in now : )!

Best,

Tim.

**Pull request merged**
