### PR TITLE
Fix Tag propType to accept string and functions

### PR DESCRIPTION
**Pull request by iagodahlem**
## Description

Change `Tag` propType to accept strings and functions, so it also accepts components rather than just regular HTML tags.

### CODE REVIEW

**Review by timhagn — COMMENTED** [review]
Looks good to me. Have you tested it already?

**Comment by timhagn** [comment]
Hi @iagodahlem,

thanks a lot for the PR : )! You wouldn't happen to know TypeScript and how to update the `index.d.ts` (for both `gbi(-es5)`)  as well, or would you?

Thanks again, best,

Tim.

**Comment by iagodahlem** [comment]
Hey @timhagn! 

Yeah, I already have an example [in one of my repos](https://github.com/iagodahlem/careers/blob/master/src/components/BackgroundImage.js#L34) and it works like a charm.

Sorry, I didn't realize those `.ts` files, I am not familiar with TS, but I can definitely do some research to update it.

**Comment by timhagn** [comment]
Hi @iagodahlem,
 
great to hear, so let's get this merged : ). I completely forgot about the changes from #77, btw., there this behavior was introduced (I'm not that fluent in TS myself ; ).

Best, Tim.

**Review by timhagn — APPROVED** [review]
Into `master` and beyond % ).

**Comment by timhagn** [comment]
Hi again, @iagodahlem,

thanks again for your changes, they have been integrated in the just published `v0.8.18` : ).

Best,

Tim.

**Comment by iagodahlem** [comment]
Perfect, thanks @timhagn! 🎉

**Pull request merged**
