### PR TITLE
Add background-position property to background image

### PR DESCRIPTION
**Pull request by r007**
Hi Tim,

Check this out. I added background-position property, it defaults to "center". However not sure if it picks up styles passed from styled-components. Can you review my changes and merge it if needed?

Thanks,
Sergey

### CODE REVIEW

**Comment by timhagn** [comment]
Thanks for the effort, though if you add `background-position: center;` to the `StyledBackgroundSection` (and thus `<BackgroundImage />`) in `gbitest` it translates (through `getBackgroundStyles()` to `background-position: 50% 50%;` which practically is `center`. Or do you get another behavior on your system (and if, please specify)?

**Comment by timhagn** [comment]
@r007 Don't get me wrong, your work is greatly appreciated! Might you just give me a `gatsby info` and some more info on your system and browser used? Cause it seems to work for me both in FF and Chromium (latest versions - and I won't let Chrome on my system, would have to create a VM for it ; ).

**Comment by r007** [comment]
Hi Tim,

I tried doing it and it doesn't work. Background position property completely ignored.

This is the latest version of **gatsby-background-image** (background position defaults to top).

before

And this is my fork (background position defaults to center, though custom position isn't passing through as well. but centered background is good enough for my purposes).

after

Here's the gatsby info:
```
  System:
    OS: Linux 4.18 Ubuntu 18.10 (Cosmic Cuttlefish)
    CPU: (8) x64 Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz
    Shell: 4.4.19 - /bin/bash
  Binaries:
    Node: 11.10.1 - ~/.nvm/versions/node/v11.10.1/bin/node
    Yarn: 1.15.2 - /usr/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v11.10.1/bin/npm
  Languages:
    Python: 2.7.15+ - /usr/bin/python
  Browsers:
    Chrome: 73.0.3683.86
    Firefox: 66.0.1
  npmPackages:
    gatsby: ^2.2.9 => 2.2.9 
    gatsby-awesome-pagination: ^0.3.4 => 0.3.4 
    gatsby-background-image: https://github.com/r007/gatsby-background-image => 0.2.73 
    gatsby-image: ^2.0.34 => 2.0.34 
    gatsby-plugin-google-analytics: ^2.0.17 => 2.0.17 
    gatsby-plugin-manifest: ^2.0.24 => 2.0.24 
    gatsby-plugin-offline: ^2.0.25 => 2.0.25 
    gatsby-plugin-react-helmet: ^3.0.10 => 3.0.10 
    gatsby-plugin-sharp: ^2.0.30 => 2.0.30 
    gatsby-plugin-styled-components: ^3.0.7 => 3.0.7 
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4 
    gatsby-remark-copy-linked-files: ^2.0.11 => 2.0.11 
    gatsby-remark-images: ^3.0.10 => 3.0.10 
    gatsby-source-filesystem: ^2.0.28 => 2.0.28 
    gatsby-transformer-remark: ^2.3.8 => 2.3.8 
    gatsby-transformer-sharp: ^2.1.17 => 2.1.17 
  npmGlobalPackages:
    gatsby-cli: 2.4.16
    gatsby: 2.1.23
```

**Comment by r007** [comment]
Here's how it looks like in inspector.

Inspector

**Comment by timhagn** [comment]
Ah, now I know what you were getting at (my fault in skimming your PR to fast, sorry therefore)!
Of course! That's why I introduced `backgroundSize` and `backgroundRepeat` in the first place,
to push them through to the pseudo-Elements (\*facepalms himself\* ; ).
And for the moment yours' is definitely a temporary solution, so I'm gonna merge it in short time : )!

Though I have to "warn" you, it mightn't make it into `0.2.8` after the alpha / beta release phases,
as I just found out, that (at least in `Chromium Version 73.0.3683.75 (Official Build) Built on Ubuntu , running on LinuxMint 19.1 (64-bit)`, have to test it for other's) styled-components' ::before & ::after` are listed in `document.styleSheets` as separate entries like `.frjXhE::after, .frjXhE::before` : ).
so we might be able to extract them!

**Comment by timhagn** [comment]
Had to merge by hand as I made some changes to `StyleUtils.js` myself in the meantime, but your changes are now included in `0.2.8-alpha2`, which I just published : ).

Though you might experience some transition problems on which I'm working at the moment.
Thanks a lot for your work and how it incentivized me digging into reading pseudo-Elements' styles : )!

**Comment by timhagn** [comment]
Now at `0.2.8-alpha3`, as we forgot to add `backgroundPosition` to `fixed` as well % ).
Thanks again!

**Comment by petrpacas** [comment]
Related to `center`=>`50% 50%`, why not just straight up have `center center` as default?

**Comment by timhagn** [comment]
@petrpacas Didn't test it, though I have a strong guess, that the browser (in my comment's case, it was Chromium, methinks) internally translates `center center` to `50% 50%` as well...

**Comment by petrpacas** [comment]
Well then, don't worry about it :)

**Pull request closed without merging**
